### ISSUE TITLE
Nested node_modules gets transpiled

### ISSUE THREAD

**Issue by ikibalnyi** [martpie/next-transpile-modules#151]
- [x] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [ ] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE FAQ (you may not get support if you remove this line)

**Are you trying to transpile a local package or an npm package?**
local package

**Describe the bug**
When transpiling local package all of its node_modules get transpiled as well:
```js
withTranspileModules(['@top/utils', '@top/libs'], { debug: true });
```
log
```
next-transpile-modules - transpiled: /Users/Dev/projects/top/apps/portal/node_modules/@top/utils/node_modules/date-fns/esm/isWeekend/index.js
next-transpile-modules - transpiled: /Users/Dev/projects/top/apps/portal/node_modules/@top/utils/node_modules/date-fns/esm/isSunday/index.js
next-transpile-modules - transpiled: /Users/Dev/projects/top/apps/portal/node_modules/@top/utils/node_modules/date-fns/esm/eachWeekendOfInterval/index.js
next-transpile-modules - transpiled: /Users/Dev/projects/top/apps/portal/node_modules/@top/utils/node_modules/date-fns/esm/_lib/requiredArgs/index.js
next-transpile-modules - transpiled: /Users/Dev/projects/top/apps/portal/node_modules/@top/utils/node_modules/date-fns/esm/endOfYear/index.js
next-transpile-modules - transpiled: /Users/Dev/projects/top/apps/portal/node_modules/@top/utils/node_modules/date-fns/esm/startOfYear/index.js
next-transpile-modules - transpiled: /Users/Dev/projects/top/apps/portal/node_modules/@top/utils/node_modules/date-fns/esm/addQuarters/index.js
next-transpile-modules - transpiled: /Users/Dev/projects/top/apps/portal/node_modules/@top/utils/node_modules/date-fns/esm/_lib/requiredArgs/index.js
next-transpile-modules - transpiled: /Users/Dev/projects/top/apps/portal/node_modules/@top/utils/node_modules/date-fns/esm/toDate/index.js
next-transpile-modules - transpiled: /Users/Dev/projects/top/apps/portal/node_modules/@top/utils/node_modules/date-fns/esm/startOfQuarter/index.js
next-transpile-modules - transpiled: /Users/Dev/projects/top/apps/portal/node_modules/@top/utils/node_modules/date-fns/esm/addWeeks/index.js
```

**To Reproduce**
Transpile any package

**Expected behavior**
Nested `node_modules` should be not be transpiled

**Setup**

- Next.js version: 10.0.3
- `next-transpile-modules` version: 6.0.0
- Node.js version: 14.15.0
- `yarn` version: 2.4.0
- Operating System: Mac Os
- Webpack: 4

**Comment by martpie** [comment]
Why should not they be transpiled?

**Comment by ikibalnyi** [comment]
Because they are `node_modules`, why would you transpile for example `lodash` if it's not told to be transpiled?

**Comment by martpie** [comment]
In what usecase would lodash be installed in the `node_modules` of your consumed package rather than at the root of your consumer `node_modules`?

**Comment by martpie** [comment]
Sidenote, on your example above, you're importing the ESM build of date-fns, which you probably don't want (you'd want CJS, unless I misunderstood something)

**Comment by ikibalnyi** [comment]
> In what usecase would lodash be installed in the `node_modules` of your consumed package rather than at the root of your consumer `node_modules`?

When consumed package has `lodash` as a dependency. In my example plugin transpiles `date-fns` package of the consumed package.

> Sidenote, on your example above, you're importing the ESM build of date-fns, which you probably don't want (you'd want CJS, unless I misunderstood something)

Thanks, will check!

**Comment by martpie** [comment]
> When consumed package has lodash as a dependency

99% of the time, `lodash` will then be installed in `node_modules`, not `node_modules/your-package/node_modules`. So I am trying to understand how this lodash got there. Are you using workspaces or a classic setup with `link:`?

**Comment by ikibalnyi** [comment]
I'm using workspaces

**Comment by paales** [comment]
This happens when there are multiple versions of the same package in use, then it gets nested

**Comment by martpie** [comment]
My point exactly. I am not yet sure if this is a bug or a feature. 🤔 I need sleep.

**Comment by martpie** [comment]
Let's say we remove transpiling for sub-`node_modules`, I could see scenarios where people complain because they need to transpile module X that is there.

In that case, they'd need to `withTranspileModules(['styleguide', 'styleguide/node_modules/lodash-es']);` for example. Which feels a bit weird.

Hence my question to @ikibalnyi: did you have any actual issue with this behavior?

**Comment by ikibalnyi** [comment]
I think it's better to be strict in this case, because transpiling all the node_modules is costly. If you want to transpile 'styleguide' I don't think you should be transpiling all of it's `node_modules` unless you specifically say to. Because most of the time it's not wanted.
Another thing is that is that it can be implemented the way that, you can say `styleguide/node_modules` and it can transpile the inner `node_modules` if needed.

**Comment by ikibalnyi** [comment]
Hm I just noticed, It looks like it's now a default behavior of yarn berry. I think they isolates all the `node_modules` within workspace modules now. So seems all the workspace modules will contain of its `node_modules` linked.

**Comment by ikibalnyi** [comment]
And from I can see now, `node_modules` appear in  workspace modules if the don't have duplicates with other modules. if module A has `lodash` and module B has `react`, both of these packages will exist only inside modules' inner `node_modules`.

**Comment by kevinmook** [comment]
This is an issue for me as well - my problem is a nested package is being transpiled but is generating a warning on every compile because it uses an anonymous function.

Not to bikeshed, and this may be beyond the scope of this particular issue, but would adding an option to exclude node_modules help avoid a breaking change? Or maybe adding a per-module config like the following (using Babel's api as inspiration):

```
withTranspileModules(['@top/utils', ['@top/libs', {node_modules: false}]], { debug: true });
```

**Comment by martpie** [comment]
Yep, I was thinking about implementing settings "per modules", this might be the way to go 👍

**Comment by alexandre-marchina** [comment]
The code introduced in https://github.com/martpie/next-transpile-modules/pull/152 that closed this issue broke our scenario here.
We've updated from 6.0.0 to 6.1.0 and started to get this error on build

```
./node_modules/process/browser.js
TypeError: .../node_modules/process/browser.js: Property left of AssignmentExpression expected node to be of a type ["LVal"] but instead got "BooleanLiteral"
```

But just to reach out, maybe you guys can help, if i revert the change introduced in #152 (directly in node_modules), everything works

Can't reproduce on another project yet, so if i manage to achieve this, i'll open another issue

**Comment by martpie** [comment]
Thank you for the report, I will try to see what is going wrong soon

**Comment by martpie** [comment]
can you tell me more about your setup? Maybe a new issue?

**Comment by alexandre-marchina** [comment]
@martpie it's a very specific scenario, but maybe being caused by a simple bug. my guess is that this check with the `path.sep` is failing: https://github.com/martpie/next-transpile-modules/blob/master/src/next-transpile-modules.js#L124

I've been debugging and this `path.sep` always returns `undefined` when running my builds. 

I have a very specific scenario where i have some integration tests in a shared internal library (in which i use next-transpile-modules to transpile in other projects), similar with what you've done [here](https://github.com/martpie/next-transpile-modules/tree/master/src/__tests__). With the `path.sep` returning `undefined`, that string split fails, and packages that don't suppose to be transpiled end up being transpiled. My tests runs inside the shared library directory, and thus it's like the whole node_modules of the _shared library's test app_ are being transpiled, with this [`include`](https://github.com/ikibalnyi/next-transpile-modules/blob/d49e3ee3bdf5b56d21fb8ccfb2cb9496771009e9/src/next-transpile-modules.js#L127) always returning `true`. Sorry if that isn't clear enough, perhaps with some time i could prepare some reproducible case. Perhaps if the name of the package being transpiled happens to be contained in that string of the full path of the module being parsed, some similar problem will happen

My setup
Next.js version: 10.0.1
next-transpile-modules version: 6.1.0
Node.js version: 10.19.0
Operating System: Ubuntu 18.04.4 
Webpack: 4

**Comment by alexandre-marchina** [comment]
I believe that the cause of `path.sep` being `undefined` it's because it's being shadowed, with `path` as function parameter "redefining" it inside the function scope: https://github.com/martpie/next-transpile-modules/blob/master/src/next-transpile-modules.js#L123

It should come from the import here: https://github.com/martpie/next-transpile-modules/blob/master/src/next-transpile-modules.js#L1

**Comment by martpie** [comment]
Thank you for getting into it, you are probably right, when I saw the `splice()[0]`, the first thing I though was "TS would have caught that and this is a code smell".

For some reasons I did not address it before the release, and it's probably what's going wrong.

**Comment by alexandre-marchina** [comment]
@martpie what would be your preferred approach to the problem? With this current implementation,  and with that bug that don't split the full path properly, i believe that check for nested modules never worked as intended since 6.1.0 landed, maybe with nested modules still being parsed. But if we manage do correct it, some other unforeseen scenarios could happen. This check could cause some false positives, specially if are nested modules with the same name compared with the ones being passed as config. I don't know, but the old implementation (the one that still depended on `generateModulesPaths`) seemed more "safe", taking in consideration that the resolved path of the module were used to match the modules

Would you prefer to revert it, or just to fix this bug?

**Comment by martpie** [comment]
This logic could be re-thought like the following: if there are multiple `/node_modules/` in the path, we ignore the file and don't transpile it.

It's a shortcut, but it looks valid to me. What do you think?

**Comment by alexandre-marchina** [comment]
>It's a shortcut, but it looks valid to me. What do you think?

I think maybe it's a good workaround, but without much certainty :sweat_smile:. In the future maybe there will be scenarios were people purposefully want to transpile a nested module (a shared library, in different versions, being used by other shared library) 

And about that

>i believe that check for nested modules never worked as intended since 6.1.0 landed, maybe with nested modules still being parsed

I've managed do reproduce here
https://github.com/alexandre-marchina/transpiled-modules-bug-repro

I've instaled different versions of `date-fns` (similar to the OP problem): one inside de transpile module, and the other directly in the nextjs project. With that, i've forced the install via `npm pack` to avoid symlinks, and `date-fns` were being nested inside "shared-ui" node_modules

```
npm ls date-fns
transpiled-modules-bug-repro@0.1.0 /workspace/external/transpiled-modules-bug-repro
├── date-fns@2.16.1 
└─┬ shared-ui@1.0.0
  └── date-fns@2.15.0 
```

If you run the build of the repro, you'll see that this nested `date-fns` it's being picked to be transpiled:

```
npm run build && npm start

> transpiled-modules-bug-repro@0.1.0 build /workspace/external/transpiled-modules-bug-repro
> next build

next-transpile-modules - the following paths will get transpiled:
  - /workspace/external/transpiled-modules-bug-repro/node_modules/shared-ui
info  - Creating an optimized production build .next-transpile-modules - transpiled: /workspace/external/transpiled-modules-bug-repro/node_modules/shared-ui/components/Button.jsx
next-transpile-modules - transpiled: /workspace/external/transpiled-modules-bug-repro/node_modules/shared-ui/components/Button.jsx
next-transpile-modules - transpiled: /workspace/external/transpiled-modules-bug-repro/node_modules/shared-ui/node_modules/date-fns/index.js
info  - Creating an optimized production build ..next-transpile-modules - transpiled: /workspace/external/transpiled-modules-bug-repro/node_modules/shared-ui/node_modules/date-fns/esm/index.js
info  - Creating an optimized production build .next-transpile-modules - transpiled: /workspace/external/transpiled-modules-bug-repro/node_modules/shared-ui/node_modules/date-fns/esm/constants/index.js
next-transpile-modules - transpiled: /workspace/external/transpiled-modules-bug-repro/node_modules/shared-ui/node_modules/date-fns/add/index.js
```

**Comment by martpie** [comment]
For this setup, is recommend using non workspaces now, they are typically used to solve these issues

**Comment by alexandre-marchina** [comment]
> For this setup, is recommend using npm workspaces now, they are typically used to solve these issues

I'm sorry, what setup? The repro was just to show you that the intended check of nested modules is not working

**Comment by mgramki21** [comment]
> The code introduced in #152 that closed this issue broke our scenario here.
> We've updated from 6.0.0 to 6.1.0 and started to get this error on build
> 
> ```
> ./node_modules/process/browser.js
> TypeError: .../node_modules/process/browser.js: Property left of AssignmentExpression expected node to be of a type ["LVal"] but instead got "BooleanLiteral"
> ```
> 
> But just to reach out, maybe you guys can help, if i revert the change introduced in #152 (directly in node_modules), everything works
> 
> Can't reproduce on another project yet, so if i manage to achieve this, i'll open another issue

Hi,
we are also facing issue for "next-transpile-modules": "6.2.0",

it is getting when we transpile our shared modules

./node_modules/process/browser.js
TypeError: ..\node_modules\process\browser.js: Property left of AssignmentExpression expected node to be of a type ["LVal"] but instead got "BooleanLiteral"

could you please help us here

**Comment by martpie** [comment]
Please open a separate issue 👍
