### ISSUE TITLE
next start errors when local package is removed after build

### ISSUE THREAD

**Issue by HosseinAgha** [martpie/next-transpile-modules#177]
- [X] I HAVE READ [THE FAQ](https://github.com/martpie/next-transpile-modules#faq) AND MY PROBLEM WAS NOT DESCRIBED THERE
- [X] I WILL GIVE 10$ TO CHARITY IF MY SOLUTION WAS ACTUALLY IN THE README/FAQ

**Are you trying to transpile a local package or an npm package?**
local package

**Describe the bug**
We use yarn's link protocol (`link:../shared-package`) in our projects (tried workspaces in many projects and we don't want to use it in this project 😄 ).   
After running `next build` we remove the local package (because we expect it to be transpiled and be part of the bundle).   
When running `next start` we get the following error:  
`next-transpile-modules - an unexpected error happened when trying to resolve "example-package"`  

**To Reproduce**
Explained above

**Expected behavior**
I think as `next-transpile-modules` __transpiles the module__ the module should not be external in serverside. Also, it should not try to resolve the packages when next.config.js is ran using `next start`.

**Setup**

- Next.js version: 10.0.3
- `next-transpile-modules` version: 6.3.0
- Node.js version: 14
- `npm`/`yarn` version: 1.22.10
- Webpack 4 or 5: 4

**Comment by HosseinAgha** [comment]
@martpie could you please explain the reason for closing the issue? Am I missing something?

**Comment by HosseinAgha** [comment]
@martpie could you please explain the reason for closing the issue? Am I missing something?

**Comment by martpie** [comment]
>  Am I missing something?

You missed a checkbox ;)

**Comment by HosseinAgha** [comment]
@martpie Checkbox added

**Comment by martpie** [comment]
I was going to write some big text on why/how/blabla, but let's try to focus on a possible resolution instead.

The questions to answer are:

- are we a 100% sure 0% of the packages transpiled are not used during `next start`
- can we use next config phases to detect when to apply this plugin? 
  - only for `PHASE_PRODUCTION_BUILD ` and `PHASE_DEVELOPMENT_SERVER `
- are we sure using phases (and a config instead of an object) will not break anyone's build?

If the answer is yes to all these questions, then we may move forward. 

cf. https://nextjs.org/docs/api-reference/next.config.js/introduction

**Comment by HosseinAgha** [comment]
Hi,  
I can answer using my point of view but I may miss some edge case:  
  - I think this will definitely create unexpected errors in the frontend bundle (how can frontend read untranspiled and unbundled portions of the package?), Plus aren't we removing the package from externals list? So everything should be in the bundle regardless of frontend or backend.
  - IMO, we should remove this plugin only from the production server-side run (`PHASE_PRODUCTION_SERVER` I guess).  
  - I think relying on this plugin (which offers a compile only functionality) for runtime is a mistake
