### ISSUE TITLE
Next.js 10.2

### ISSUE THREAD

**Issue by martpie** [martpie/next-transpile-modules#195]
- [x] Does it automatically enable Webpack 5?
- [x] Should we disable symlinks resolution by default?
- [x] Other things to include?

**Comment by emrysal** [comment]
This is fast!

I've ran a test run with future: true in Next.js - seems to work just fine with 10.2. I did have to explicitly enable Webpack 5 due to the reason mentioned below.

 Interestingly I found out that Next.js turns off webpack 5 if next-transpile-modules is enabled. See the following:
```javascript
const withTM = require('next-transpile-modules')(['...']);

module.exports = withTM({
  typescript: {
    ignoreBuildErrors: true,
  },
});
```
Result: `info  - Using webpack 4. Reason: custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5`

But with this config:
```javascript
module.exports = {
  typescript: {
    ignoreBuildErrors: true,
  },
};
```
Result: `info  - Using webpack 5. Reason: no custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5`

**Comment by martpie** [comment]
Thanks for sharing! That is definitely useful!

What happens when you explicitly set future.webpack5 to `true`?

**Comment by emrysal** [comment]
The output when I explicitly toggle on the future.webpack5 option:

`info  - Using webpack 5. Reason: future.webpack5 option enabled https://nextjs.org/docs/messages/webpack5
next-transpile-modules - WARNING experimental Webpack 5 support enabled`

**Comment by martpie** [comment]
Well that's fine, I am currently working on not making it experimental anymore 😄 hopefully by tonight (western europe time) I'll have something.
