### ISSUE TITLE
Does not work with babel-plugin-module-resolver

### ISSUE THREAD

**Issue by sourcesoft** [martpie/next-transpile-modules#21]
Hello :) I was trying to use this library with `next-redux-wrapper` since it exports ESM and Nextjs for some reason doesn't transpile it.
config (`react-spring` is working tho):
```
transpileModules: ['next-redux-wrapper', 'react-spring'],
```
I'm importing it like this which should work
```
import withRedux from 'next-redux-wrapper'
```

However I'm getting 
```
./pages/_app.js
Attempted import error: 'next-redux-wrapper' does not contain a default export (imported as 'withRedux')
```
Apparently `next-redux-wrapper` is using Lerna too, I'm not sure if it's related to this issue or not. However the way I see it I have the right package in `node_modules/next-redux-wrapper` so it should be an issue

[Link to `next-redux-wrapper` entry points](https://github.com/kirill-konshin/next-redux-wrapper/blob/master/packages/wrapper/package.json)

My `.babelrc` if it helps:
```
{
  "presets": [
    "next/babel"
  ],
  "plugins": [
    [
      "styled-components",
      { "ssr": true }
    ],
    ["@babel/plugin-proposal-decorators", {
      "legacy": true
    }],
    [
      "inline-import",
      {
        "extensions": [".css"]
      }
    ],
    [
      "import",
      {
        "libraryName": "antd",
        "style": "css"
      }
    ],
    ["module-resolver", {
      "root": ["./"]
    }]
  ]
}
```
FYI I'm following this issue in Next Spectrum channel too https://spectrum.chat/next-js/general/problem-with-importing-es6-modules~b0e6036d-3b60-438c-b3b1-1041ed7ba1af

**Comment by sourcesoft** [comment]
I removed the package from `transpileModules` array and instead added
```
config.resolve.alias = {
  ...config.resolve.alias,
  'next-redux-wrapper': require.resolve('next-redux-wrapper/lib'),
};
```
to `next.config.js` and fixed the issue for me for transpiling.

**Comment by martpie** [comment]
I think there is an issue with Babel's module resolve I need to investigate. You are not the first with a similar issue.

**Comment by alexkrautmann** [comment]
> I removed the package from `transpileModules` array and instead added ...

I think this works in your case because the `next-redux-wrapper` package is built to `lib`.

I am having a slightly different issue when trying to combine this with `babel-plugin-module-resolver` for use in a monorepo. The problem is that when you use `babel-plugin-module-resolver`, the module name this next plugin sees has already been transformed.

Notice here the app's babel config aliases monorepo imports the package's `src` directory.
```
// @myapp/web-app - babel.config.js

module.exports = function(api) {
  api.cache(true);
  const presets = [
    'next/babel',
    ['@babel/preset-typescript', { isTSX: true, allExtensions: true }]
  ];
  const plugins = [
    'styled-components',
    [
      'module-resolver',
      {
        alias: { '^@myapp/(.+)': '../\\1/src' },
      },
    ],
  ];

  return {
    presets,
    plugins,
  };
};
```

In the app's next config, I set transpileModules to the monorepo's scope `@myapp`:
```
// @myapp/web-app - next.config.js

module.exports = withBundleAnalyzer(
  withTypescript(
    withTranspileModules({
      transpileModules: ['@myapp'],
    }),
    ...
  ),
);
```

But next.js compilation fails with:

```
Failed to compile.

../biz/src/index.tsx 14:25
Module parse failed: Unexpected token (14:25)
You may need an appropriate loader to handle this file type.
| `;
| 
> export const Biz = () => <View><Outer>biz <Inner>baz</Inner></Outer></View>
|

```

However, if I set transpileModules to the result of the aliased filenames, it works:

```
// @myapp/web-app - next.config.js

module.exports = withBundleAnalyzer(
  withTypescript(
    withTranspileModules({
      transpileModules: ['../biz/src/index.tsx'],
    }),
    ...
  ),
);
```

I'm not sure of a good way to fix this off the top of my head. I see the same issue when I alias using webpack instead of babel.

**Comment by martpie** [comment]
@sourcesoft quick question: how can you know that the problem is coming from babel-plugin-resolver and not the next-redux-wrapper package

@alexkrautmann I am not understanding the problem, why do you make use of `babel-plugin-module-resolver` in your project? `@myapp` should be in your node_modules no? You do not need to alias it, you could just `import { something } from '@myapp/subpackage'`

**Comment by martpie** [comment]
Just as a clarification, **`next-transpile-modules` only transpile code located in `node_modules`**. It does not transpile external code that is not in your node_modules.

This is why you have to use Yarn workspaces or npm symlinks to work with local packages.

**Comment by alexkrautmann** [comment]
Thanks for the followup @martpie, hopefully I'm not just piling onto this issue with something unrelated. I also apologize for these lengthy replies, I find that monorepo setups like this involve a lot of tools and setup. I've actually come across [monorepo-typescript-next-the-sane-way](https://github.com/martpie/monorepo-typescript-next-the-sane-way) before, but I didn't realize you were the author on that repo when I first posted here.

To be clear, I am using Yarn Workspaces for the monorepo. Its kind of a different use-case than most people will use this package for, but it does show a limitation of this package when used with babel or webpack resolve aliases.

I was able to find a workaround by specifying a regex for `transpileModules`. This regex matches aliased monorepo package imports from inside a package in the monorepo. It isn't pretty.

```
// @myapp/web-app - next.config.js

module.exports = withBundleAnalyzer(
  withTypescript(
    withTranspileModules({
      transpileModules: ['\.\./.+/src/.+\.tsx?'],
      ...
    }),
  ),
);
```

This is needed because webpack in `@myapp/web-app` only sees the aliased module name instead of original module name. So to webpack, `import { biz } from '@myapp/biz'` is seen as `import { biz } from '../biz/src/index.ts'`. In order for webpack to transpile `biz`, babel-loader needs to have an `include` that matches '../biz/src/index.ts' instead of an `include` that matches `@myapp/biz`.

I'm thinking I need to take a step back and look for another approach. I might just end up watching and transpiling shared monorepo packages to avoid some of these hacks and workarounds. We don't need to discuss this here since it might be off-topic, but I am definitely interested in any information or insight you have.

<details>
<summary>Some more background on the monorepo</summary>

Both the Next webapp and the the other monorepo packages use typescript, and each package has their TS in their respective `src` directory. I am using `@babel/preset-typescript` to actually transpile the typescript and the typescript compiler to type-check the typescript. The typescript compiler handles pointing to each `src` by using [typescript pathMapping](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping). I've used pathMapping like this in other projects where the typescript compiler is responsible for transpilation, and seen other use this method as well.

I am basically using `babel-plugin-module-resolver` in the webapp (and in each package if they depend on each other) to replicate typescript pathMapping since `@babel/preset-typescript` does not actually read path config from `tsconfig.json`.

The reason for doing this is to avoid having to always be watching and rebuilding each dependent package. It also leads to less tooling to install since I can avoid having to use things like `ts-jest`, `typescript-loader`, and other packages that wrap the typescript compiler.

Here is how my monorepo is organized:

```
.
├── packages                        # all monorepo packages
│   ├── ...
│   ├── biz                         # @myapp/biz - consumed in @myapp/web-app
│   │   ├── ...
│   │   ├── src                         # typescript source
│   │   │   ├── ...
│   │   │   └── index.ts                    # biz entry
│   │   ├── ...
│   │   ├── package.json
│   │   └── tsconfig.json               # tsconfig used for typechecking only
│   ├── web-app                     # @myapp/web-app - Next.js app
│   │   ├── ...
│   │   ├── pages                         # typescript source
│   │   │   ├── ...
│   │   │   └── index.tsx                 # Next.js homepage, consumes @myapp/biz by pointing to its src
│   │   ├── ...
│   │   ├── babel.config.js             # babel config uses babel-plugin-module-resolver
│   │   ├── package.json
│   │   └── tsconfig.json               # tsconfig used for typechecking only
│   └── ...
├── package.json                    # monorepo package.json
├── tsconfig.json                   # base tsconfig, extended in monorepo packages
└── ...
```

</details>

**Comment by martpie** [comment]
I think I understand your problem (tell me if I don't), and I can tell you over-engineered your solution :)

Let's take a step back.

We have two projects (I'm renaming them for the sake of understanding:

- `website`: a Next.js app
- `styleguide` a classic TS repo exposing some components (Buttons, ...)

Let's say [we configured Yarn workspaces correctly](https://github.com/zeit/next.js/tree/canary/examples/with-yarn-workspaces).

We try to import a button from the `styleguide` directory:

```
import { Button } from 'styleguide';
```

Webpack **will** resolve this correctly thanks to Yarn workspaces who installed `styleguide` as a modules in your root `node_modules`. 

Problem: we import a `.ts` file, but Babel by default, ignores everything coming from `node_modules` (most of the time, the modules you installed are already transpiled, but not `styleguide`, as it is a local package).

Until there, **we did not speak about `babel-plugin-module-resolver` at all**.

What does that mean? That means webpack is trying to load a modules written in TypeScript, but it does not know what to do with it (no loaders are associated to files coming from `node_modules`). Then it throws `cannot compile: unexpected token blabla`.

**How do we solve this?**

- We need to tell Webpack to apply next.js loaders (which includes Babel) on `node_modules/styleguide`.
- We need to tell Webpack dev server to watch for changes in `<root>/node_modules/styleguide`, and recompile if needed.

This is exactly what `next-transpile-modules` does.

This plugin will update some ignore/include rules of Next.js's Babel and Webpack to make it believe `styleguide` is part of your project and need to be transpiled with the same loaders as the rest of your Next.js app, BUT all the other modules (everything that is not `styleguide`) should not be transpiled as they already are.

Done.

- Yarn will install `styleguide` in your root `node_modules` (via workspaces)
- Webpack will resolve the import by finding it is in your root `node_modules`
- Wepback will apply Babel to these files, and will watch for changes
- **No need for `babel-plugin-module-resolver`**

---

I encourage you to check these two examples:

- yarn workspaces: https://github.com/zeit/next.js/blob/canary/examples/with-yarn-workspaces/packages/web-app/pages/index.js#L1
- npm symlinks: https://github.com/martpie/monorepo-typescript-next-the-sane-way/blob/master/website/pages/index.tsx#L2

You do not need `babel-plugin-module-resolver` to resolve modules from `node_modules`. (but you **may** need it for code **in** the Next.js folder, ti import reducers or styles easily for example)

---

Hope it makes sense :)

**Comment by alexkrautmann** [comment]
I actually started this repo from the `with-yarn-workspaces` example. Since I also want to publish the component packages, I had added package.json#main set to `dist/index.js`. This is where the problem was coming from. Without `babel-plugin-module-resolver`, web-app will point to bar's `dist/index.js` instead of `src/index.tsx` when it resolves the module via workspaces.

I came up with another workaround for this problem that seems to have the least tradeoffs. I ended up giving each shared package an index.js and index.ts at their roots instead of defining `package.json#main`. The `index.js` exports the dist folder and the `index.ts` exports the `src` folder. Then I overrode `resolve.extensions` in the web-app to prefer `.ts(x)` files over `.js(x)`. Its a somewhat odd setup and requires extra files, but I can publish the separate packages and let next.js transpile local packages with watching. 

Node module resolution can definitely play tricks on you sometimes. I'm going to push up an example repo of this method shortly. Thanks for all the help, much appreciated!

**Comment by martpie** [comment]
I think that if you need to publish AND use a package, things will get tricky indeed.

The only easy workaround I see would be to `import stuff from 'youpackage/src/index.tsx'`, which is a little bit dirty.

Or you compile your TS library with `tsc --watch` when developing (without forgetting to generate definition files) 🤔

**Comment by JulienKode** [comment]
> I actually started this repo from the `with-yarn-workspaces` example. Since I also want to publish the component packages, I had added package.json#main set to `dist/index.js`. This is where the problem was coming from. Without `babel-plugin-module-resolver`, web-app will point to bar's `dist/index.js` instead of `src/index.tsx` when it resolves the module via workspaces.
> 
> I came up with another workaround for this problem that seems to have the least tradeoffs. I ended up giving each shared package an index.js and index.ts at their roots instead of defining `package.json#main`. The `index.js` exports the dist folder and the `index.ts` exports the `src` folder. Then I overrode `resolve.extensions` in the web-app to prefer `.ts(x)` files over `.js(x)`. Its a somewhat odd setup and requires extra files, but I can publish the separate packages and let next.js transpile local packages with watching.
> 
> Node module resolution can definitely play tricks on you sometimes. I'm going to push up an example repo of this method shortly. Thanks for all the help, much appreciated!

Have you find any other solution @alexkrautmann I want to do the same as you, I have a package that I need to publish so I have a dist but I want next to transpile theses modules 

So I ended up doing this:

```
      config.resolve.alias = {
          ...config.resolve.alias,
          '@project': '@org/project/src',
        };
```

I works for a package but does not works for another

**Comment by JulienKode** [comment]
@martpie does this way of configuring alias is good ?
```
config.resolve.alias = {
          ...config.resolve.alias,
          '@project': '@org/project/src',
};
```

Or it can create some issues
